#!/usr/bin/env python3

import os
import platform
from time import sleep

def refresh():
    if platform.system()=='Windows':
        os.system("cls")
    elif platform.system()=='Linux' or platform.system()=='Darwin':
        os.system("clear")

trainPath = os.path.join(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'setup'), 'train')
shellPath = os.path.join(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'setup'), 'shell')

refresh()
if platform.system()=='Linux' or platform.system()=='Darwin':
    print("Press 1 to train :: Press 0 to shell")
    choice = int(input(":: "))
    if choice==1:
        os.system(f"chmod +x {trainPath}")        
        os.system(f"{trainPath}")
    elif choice==0:
        os.system(f"chmod +x {shellPath}")        
        os.system(f"{shellPath}")
    else:
        print("error.")
        sleep(3)