#!/usr/bin/env bash
conda_base=$(conda info --base)
conda_source="$conda_base/etc/profile.d/conda.sh"
source $conda_source

conda activate d33pster
# cd ..
clear
echo -n "train sequence initialised ..."
sleep 3
echo " "
echo " "
rasa train